version: "3.9"
services:

  # 🛠️ Portainer - Administración Docker
  portainer:
    image: portainer/portainer-ce:latest
    container_name: 🛠️-portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "9000:9000"
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - portainer_data:/data
    networks:
      - dockmon

  # 🤖 Controller Bot - Telegram
  controller-bot:
    image: dgongut/docker-controller-bot:latest
    container_name: 🤖-controller-bot
    restart: always
    tty: true
    environment:
      - TZ=${TZ}
      - CONTAINER_NAME=controller-bot
      - TELEGRAM_TOKEN=${BOT_TOKEN}
      - TELEGRAM_ADMIN=${CHAT_ID}
      - CHECK_UPDATE_EVERY_HOURS=72
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config
    networks:
      - dockmon

  # 🌐 Technitium DNS - Servidor DNS
  technitium-dns:
    image: technitium/dns-server:latest
    container_name: 🌐-technitium-dns
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "127.0.0.1:5380:5380"
    environment:
      - DNS_SERVER_DOMAIN=home
      - DNS_SERVER_ADMIN_PASSWORD=${DNS_ADMIN_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./technitium/data:/etc/dns
    networks:
      - dockmon
    security_opt:
      - no-new-privileges:true

volumes:
  portainer_data:
networks:
  dockmon:
    driver: bridge
